version: "3.9"

services:
    app:
        container_name: container_digitalMoroccoBack_api
        image: image_digitalMoroccoBack_api
        restart: always
        build:
            context: .
            dockerfile: Dockerfile
            target: base
        ports:
            - "${PORT}:${PORT}"